spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:data/ddl.sql
      mode: always

mybatis:
  mapper-locations: mapper/*.xml

server:
  port: 8080